# Generated by Django 5.0.1 on 2025-10-19 20:30

from django.db import migrations, models


def rename_admin_to_manager(apps, schema_editor):
    """Rename all ADMIN users to MANAGER and remove superuser/staff privileges."""
    User = apps.get_model('users', 'User')

    # Update all ADMIN users to MANAGER
    User.objects.filter(role='ADMIN').update(role='MANAGER')

    # Remove superuser and staff privileges from all users
    User.objects.all().update(is_staff=False, is_superuser=False)


def reverse_rename(apps, schema_editor):
    """Reverse migration - rename MANAGER back to ADMIN."""
    User = apps.get_model('users', 'User')
    User.objects.filter(role='MANAGER').update(role='ADMIN')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('TEACHER', 'Teacher'), ('STAFF', 'Staff'), ('MANAGER', 'Manager')], default='TEACHER', max_length=10, verbose_name='User Role'),
        ),
        migrations.RunPython(rename_admin_to_manager, reverse_rename),
    ]
