# Generated by Django 5.0.1 on 2025-10-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_admin_to_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_auditor',
            field=models.BooleanField(default=False, help_text='User can access audit checklist and mark items as damaged/lost', verbose_name='Auditor Permission'),
        ),
    ]
