# Generated by Django 5.0.1 on 2025-10-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disable_expiration_emails',
            field=models.BooleanField(default=False, help_text='Opt out of email notifications for expiring requests (web notifications will still be sent)', verbose_name='Disable Expiration Warning Emails'),
        ),
    ]
