# Generated by Django 5.0.1 on 2025-10-19 19:13

import items.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Item Name')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Model/Version')),
                ('asset_id', models.CharField(help_text='Unique asset identification number', max_length=50, unique=True, verbose_name='Asset ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to=items.models.item_image_path, verbose_name='Item Image')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Purchase Price')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Location/Room')),
                ('status', models.CharField(choices=[('NORMAL', 'Normal (In Use)'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost'), ('REPAIR', 'Under Repair'), ('PENDING_INSPECTION', 'Pending Inspection'), ('REMOVED', 'Removed from System')], default='NORMAL', max_length=20, verbose_name='Status')),
                ('date_acquired', models.DateField(help_text='Date when item was first added to system', verbose_name='Date Acquired')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the item', null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Item Category',
                'verbose_name_plural': 'Item Categories',
                'ordering': ['name'],
            },
        ),
    ]
