# Generated by Django 5.0.1 on 2025-10-19 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='current_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_items', to=settings.AUTH_USER_MODEL, verbose_name='Current Owner'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='items.itemcategory', verbose_name='Category'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['asset_id'], name='items_item_asset_i_0c8108_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['current_owner', 'status'], name='items_item_current_33696a_idx'),
        ),
    ]
