# Generated by Django 5.0.1 on 2025-10-21 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='current_location',
            field=models.ForeignKey(blank=True, help_text='Current physical location (updated by item owner)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_current', to='locations.location', verbose_name='Current Location'),
        ),
        migrations.AddField(
            model_name='item',
            name='home_base_location',
            field=models.ForeignKey(blank=True, help_text='Default location where item belongs (set by Staff)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_home_base', to='locations.location', verbose_name='Home Base Location'),
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Location/Room (Deprecated - use home_base_location)'),
        ),
    ]
