# Generated by Django 5.0.1 on 2025-10-21 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_current_location_item_home_base_location_and_more'),
        ('locations', '0002_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='location_description',
            field=models.TextField(blank=True, default='', help_text='Free-form location description (e.g., "Building 1, floor 2")', verbose_name='Location Description'),
        ),
        migrations.AddField(
            model_name='item',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Room code (e.g., sc201, sc202)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='locations.room', verbose_name='Room'),
        ),
    ]
