# Generated by Django 5.0.1 on 2025-10-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_location_description_item_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
