# Generated by Django 5.0.1 on 2025-10-26 11:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_itemcategory_updated_at'),
        ('locations', '0002_room'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['category'], name='items_item_categor_ac6954_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['status'], name='items_item_status_819478_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['date_acquired'], name='items_item_date_ac_c454e0_idx'),
        ),
    ]
