# Generated by Django 5.0.1 on 2025-10-26 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0002_room'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, help_text='Leave blank for all departments', max_length=100, null=True, verbose_name='Department')),
                ('is_global', models.BooleanField(default=False, help_text='Auditor can audit ALL items regardless of location/department', verbose_name='Global Access')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auditor', models.ForeignKey(limit_choices_to={'is_auditor': True}, on_delete=django.db.models.deletion.CASCADE, related_name='auditor_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Auditor')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditor_assignments', to='locations.location', verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Auditor Assignment',
                'verbose_name_plural': 'Auditor Assignments',
                'ordering': ['auditor', '-created_at'],
                'indexes': [models.Index(fields=['auditor'], name='audit_audit_auditor_07f346_idx'), models.Index(fields=['location'], name='audit_audit_locatio_032a38_idx'), models.Index(fields=['is_global'], name='audit_audit_is_glob_8648f0_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='auditorassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('location__isnull', False)), fields=('auditor', 'location'), name='unique_auditor_location'),
        ),
        migrations.AddConstraint(
            model_name='auditorassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', False)), fields=('auditor', 'department'), name='unique_auditor_department'),
        ),
    ]
