# Generated by Django 5.0.1 on 2025-10-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransferLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_forced', models.BooleanField(default=False, help_text='True if this was a forced transfer by Admin', verbose_name='Forced Transfer')),
            ],
            options={
                'verbose_name': 'Transfer Log',
                'verbose_name_plural': 'Transfer Logs',
                'ordering': ['-transferred_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('ASSIGN', 'Assign to User'), ('RETURN', 'Return to Staff')], max_length=10, verbose_name='Request Type')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10, verbose_name='Status')),
                ('notes', models.TextField(blank=True, help_text='Reason for transfer or condition notes (for returns)', null=True, verbose_name='Notes')),
                ('new_status', models.CharField(blank=True, help_text='For returns: Status to set when accepted (e.g., NORMAL, DAMAGED, REPAIR)', max_length=20, null=True, verbose_name='New Item Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When request was accepted/rejected', null=True, verbose_name='Resolved At')),
            ],
            options={
                'verbose_name': 'Transfer Request',
                'verbose_name_plural': 'Transfer Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
