# Generated by Django 5.0.1 on 2025-10-19 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0002_initial'),
        ('transfers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transferlog',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_sent_logs', to=settings.AUTH_USER_MODEL, verbose_name='From User'),
        ),
        migrations.AddField(
            model_name='transferlog',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_logs', to='items.item', verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='transferlog',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_received_logs', to=settings.AUTH_USER_MODEL, verbose_name='To User'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_requests_sent', to=settings.AUTH_USER_MODEL, verbose_name='From User'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='items.item', verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_requests_received', to=settings.AUTH_USER_MODEL, verbose_name='To User'),
        ),
        migrations.AddField(
            model_name='transferlog',
            name='request',
            field=models.ForeignKey(blank=True, help_text='Reference to original request (null for forced transfers)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='transfers.transferrequest', verbose_name='Transfer Request'),
        ),
        migrations.AddIndex(
            model_name='transferrequest',
            index=models.Index(fields=['status', 'to_user'], name='transfers_t_status_2b1a95_idx'),
        ),
        migrations.AddIndex(
            model_name='transferrequest',
            index=models.Index(fields=['item', 'status'], name='transfers_t_item_id_f3f77c_idx'),
        ),
        migrations.AddIndex(
            model_name='transferlog',
            index=models.Index(fields=['item', '-transferred_at'], name='transfers_t_item_id_be17d2_idx'),
        ),
        migrations.AddIndex(
            model_name='transferlog',
            index=models.Index(fields=['from_user', '-transferred_at'], name='transfers_t_from_us_a5dd86_idx'),
        ),
        migrations.AddIndex(
            model_name='transferlog',
            index=models.Index(fields=['to_user', '-transferred_at'], name='transfers_t_to_user_5190c7_idx'),
        ),
    ]
