# Generated by Django 5.0.1 on 2025-10-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrequest',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Request expires 7 days after creation', null=True, verbose_name='Expires At'),
        ),
    ]
