# Generated by Django 5.0.1 on 2025-10-26 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_itemcategory_updated_at'),
        ('transfers', '0003_transferrequest_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferlog',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_logs', to='items.item', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_requests', to='items.item', verbose_name='Item'),
        ),
    ]
