# Generated by Django 5.0.1 on 2025-10-26 11:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_item_items_item_categor_ac6954_idx_and_more'),
        ('transfers', '0004_alter_transferlog_item_alter_transferrequest_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transferrequest',
            index=models.Index(fields=['expires_at'], name='transfers_t_expires_3bb873_idx'),
        ),
        migrations.AddIndex(
            model_name='transferrequest',
            index=models.Index(fields=['from_user'], name='transfers_t_from_us_7c5194_idx'),
        ),
        migrations.AddConstraint(
            model_name='transferrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('item',), name='unique_pending_request_per_item'),
        ),
    ]
