# Generated by Django 5.0.1 on 2025-10-26 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_item_items_item_categor_ac6954_idx_and_more'),
        ('transfers', '0005_transferrequest_transfers_t_expires_3bb873_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrequest',
            name='expiration_extended_until',
            field=models.DateTimeField(blank=True, help_text='Admin-extended expiration deadline', null=True, verbose_name='Extended Until'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='manually_expired_by',
            field=models.ForeignKey(blank=True, help_text='Manager who manually expired this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manually_expired_requests', to=settings.AUTH_USER_MODEL, verbose_name='Manually Expired By'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='original_item_status',
            field=models.CharField(blank=True, help_text='Item status before PENDING_INSPECTION (for RETURN requests)', max_length=20, null=True, verbose_name='Original Item Status'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='warning_24h_sent',
            field=models.BooleanField(default=False, help_text='Whether 24-hour expiration warning has been sent', verbose_name='24-Hour Warning Sent'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='warning_48h_sent',
            field=models.BooleanField(default=False, help_text='Whether 48-hour expiration warning has been sent', verbose_name='48-Hour Warning Sent'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='transferrequest',
            index=models.Index(fields=['status', 'expires_at'], name='transfers_t_status_fc7a88_idx'),
        ),
        migrations.AddIndex(
            model_name='transferrequest',
            index=models.Index(fields=['status', 'warning_48h_sent'], name='transfers_t_status_f55771_idx'),
        ),
        migrations.AddIndex(
            model_name='transferrequest',
            index=models.Index(fields=['status', 'warning_24h_sent'], name='transfers_t_status_2680c5_idx'),
        ),
    ]
