# Generated by Django 5.0.1 on 2025-10-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(help_text='Building name or number', max_length=100, verbose_name='Building')),
                ('floor', models.CharField(help_text='Floor number or name', max_length=50, verbose_name='Floor')),
                ('room', models.CharField(help_text='Room number (e.g., 201-254)', max_length=50, verbose_name='Room')),
                ('description', models.TextField(blank=True, help_text='Additional location details', null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive locations are hidden from selection', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['building', 'floor', 'room'],
                'indexes': [models.Index(fields=['building', 'floor'], name='locations_l_buildin_6c92f4_idx'), models.Index(fields=['is_active'], name='locations_l_is_acti_9f2958_idx')],
                'unique_together': {('building', 'floor', 'room')},
            },
        ),
    ]
