# Generated by Django 5.0.1 on 2025-10-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Room identifier (e.g., sc201, sc202)', max_length=50, unique=True, verbose_name='Room Code')),
                ('description', models.CharField(blank=True, help_text='Optional room description', max_length=200, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive rooms are hidden from selection', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='locations_r_code_f1177c_idx'), models.Index(fields=['is_active'], name='locations_r_is_acti_0b835b_idx')],
            },
        ),
    ]
