# Generated by Django 5.0.1 on 2025-10-21 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0003_item_current_location_item_home_base_location_and_more'),
        ('transfers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('NEW_REQUEST', 'New Transfer Request'), ('REQUEST_ACCEPTED', 'Request Accepted'), ('REQUEST_REJECTED', 'Request Rejected'), ('REQUEST_EXPIRING_SOON', 'Request Expiring Soon'), ('REQUEST_EXPIRED', 'Request Expired'), ('ITEM_DAMAGED', 'Item Marked as Damaged'), ('ITEM_LOST', 'Item Marked as Lost'), ('ITEM_FOUND', 'Lost Item Found')], max_length=30, verbose_name='Type')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
                ('related_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='items.item', verbose_name='Related Item')),
                ('related_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='transfers.transferrequest', verbose_name='Related Request')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx')],
            },
        ),
    ]
